class DNOREnvironment:
    TacacsUserName = "iadmin"
    TacacsPassword = "iadmin"
    HostUser = "dn"
    HostPassword = "drive1234!"
    ConnectionPort = "22"
    cliuser = "dnroot"
    clipassword = "dnroot"
    Shelluser = "dn"
    Shellpassword = "drivenets"
